### ISSUE TITLE
Implement undo & redo feature

### ISSUE THREAD

**Issue by m1ksu** [digabi/mathquill#10]
The lack of an undo function is an obvious flaw in Mathquill as every wrong or accidental keypress risks the user losing their mathematical expressions. To save on the frustration such a thing causes, the addition of an undo and redo feature would be highly appreciated.

This has been on open issue on the main Mathquill repository for almost 11 years now. A few people have voiced their frustrations and shared their own implementations for the feature on it: https://github.com/mathquill/mathquill/issues/5. 

Perhaps one of these (or an original implementation) could be implemented into the Digabi project's fork of Mathquill?

**Comment by eeroan** [comment]
Undo is already implemented in the examination system.

**Comment by m1ksu** [comment]
It is not implemented within the equation editor itself, which is why I initially opened the issue on this repository instead of the rich-text-editor repository. 

Demonstration of the issue:
![undo](https://user-images.githubusercontent.com/22960424/154060066-0c9c7d7c-04c9-4d73-8864-e940f8f87099.gif)
