### ISSUE TITLE
Build fails on some platforms

### ISSUE THREAD

**Issue by pesasa** [digabi/mathquill#6]
Commit 3eeff3a59 (`\mathbb{}`) introduces a dependency between `src/commands/math/commands.js` and `src/commands/math/basicSymbols.js`. Variable `Variable` is defined in `basicSymbols.js` and is used in `commands.js`. On some platforms these files are catenated into `mathquill.js` in wrong order. This breaks Mathquill.

In `Makefile` (line 50) these files are included to build as:
```
  $(SRC_DIR)/commands/math/*.js
```
However, GNU Make does not guarantee the order of files given as wildcards. In my case the files were catenated in wrong order.

My platform:
- Ubuntu 16.04
- GNU Make 4.1

**Comment by eeroan** [comment]
Fixed by https://github.com/digabi/mathquill/pull/8
